fragment UserFragment on User {
  id
  firstName
  lastName
  email
}

mutation Login($input: LoginInput!) {
  login(input: $input) {
    token
    user {
      ...UserFragment
    }
  }
}

query GetUserByEmail($email: String!) {
  getUserByEmail(email: $email) {
    email
  }
}

# query GetUsers {
#   getUsers {
#     ...UserFragment
#   }
# }

# query GetUserToken($username: String!, $password: String!) {
#   getUserToken(username: $username, password: $password) {
#     accessToken
#   }
# }

mutation CreateUser($input: CreateUserInput!) {
  createUser(input: $input) {
    token
    user {
      ...UserFragment
    }
  }
}
