fragment UserFragment on User {
  id
  firstName
  lastName
  email
  avatar
  friends {
    id
    firstName
    lastName
    email
    avatar
  }
}

mutation Login($input: LoginInput!) {
  login(input: $input) {
    token
    user {
      ...UserFragment
    }
  }
}

mutation CreateUser($input: CreateUserInput!) {
  createUser(input: $input) {
    token
    user {
      ...UserFragment
    }
  }
}
