fragment UserFragment on User {
  id
  firstName
  lastName
  email
}

query GetToken($id: String!) {
  getUserById(id: $id) {
    ...UserFragment
  }
}

# query GetUsers {
#   getUsers {
#     ...UserFragment
#   }
# }

# query GetUserToken($username: String!, $password: String!) {
#   getUserToken(username: $username, password: $password) {
#     accessToken
#   }
# }

mutation CreateUser($input: CreateUserInput!) {
  createUser(input: $input) {
    token
    user {
      ...UserFragment
    }
  }
}
