type Chat {
  id: ID!
  participants: [User]!
  logo: String
  messages: [Message]
  settings: ChatSettings
}

type ChatSettings {
  testField: String
}

type Query {
  getChats: [Chat]
  getChatById(chatId: ID!): Chat
}

type Mutation {
  createChat: Chat!
}

type Subscription {
  newChat: Chat!
}
