type Message {
  id: ID!
  content: String!
  author: User!
  chatId: ID!
  createdAt: String!
  lastEdit: String
}

type Chat {
  id: ID!
  isDialog: Boolean!
  title: String!
  participants: [User]!
  logo: String
  messages: [Message] # pagination will live here (it will become a sub-query)
  settings: ChatSettings
}

type ChatSettings {
  testField: String
}

type Query {
  getChats: [Chat]
  getChatById(chatId: ID!): Chat
}

type Mutation {
  createChat(participants: [ID!]!, title: String!): Chat!
  createMessage(content: String!, chatId: String!): Message!
  deleteChatById(chatId: ID!): Chat!
  deleteMessageById(messageId: ID!): Message!
  editMessage(messageId: ID!, newContent: String!): Message!
}

type Subscription {
  newChat: Chat!
  newMessage(chatId: ID!): Message!
  messageEdited(chatId: ID!): Message!
}
