type Query {
  getMessages(chatId: ID!): [Message]
  getMessage(id: ID!): Message
}

type Mutation {
  createMessage(content: String!, chatId: ID!): Message!
}

type Subscription {
  messageCreated(chatId: ID!): Message!
}

type Message {
  id: ID!
  author: User!
  content: String!
  createdAt: String!
  lastEdit: String
}
