type Message {
  id: ID!
  content: String!
  author: ID!
  receivers: [ID!]!
  createdAt: String!
  lastEdit: String
}

type Query {
  getMessages: [Message]
}

type Mutation {
  createMessage(content: String!): Message!
}

type Subscription {
  newMessage: Message!
}
