type Message {
  id: ID!
  content: String!
  author: User!
  chatId: ID!
  createdAt: String!
  lastEdit: String
}

type Query {
  getMessages(chatId: ID!): [Message]
}

type Mutation {
  createMessage(content: String!, chatId: String!): Message!
}

type Subscription {
  newMessage: Message!
}
