type Post {
  id: ID!
  author: ID!
  createdAt: String!
  lastEdit: String
  comments: [CommentModel]
}

type Query {
  getPosts: [Post]
  getPost(id: ID!): Post
}

type Subscription {
  newPost: Post!
}

type Mutation {
  createPost: Post
}

type CommentModel {
  id: ID!
  author: ID!
  createdAt: String!
  lastEdit: String
  likes: [ID]
}
