type Query {
  getPosts: [Post]
  getPost(id: ID!): Post
}

type Subscription {
  newPost(token: String!): Post!
}

type Mutation {
  createPost(token: String!): Post!
}

type Post {
  id: ID!
  author: ID!
  createdAt: String!
  comments: [CommentModel]
}

type CommentModel {
  id: ID!
  author: ID!
  createdAt: String!
  lastEdit: String
  likes: [ID]
}
