type User {
  guid: ID!
  username: String!
  password: String!
}

type Query {
  getUser(token: String!): User
  getUsers: [User]
  getUserToken(username: String!, password: String!): AccessToken
}

type Mutation {
  createUser(input: CreateUserInput!): User
}

input CreateUserInput {
  username: String!
  password: String!
}

type AccessToken {
  accessToken: String!
}
