query GetFeed {
  getAllPosts {
    id
    author {
      id
    }
  }
}

query GetFriendFeed {
  getFriendPosts {
    id
    author {
      id
    }
  }
}

query GetPostById($id: ID!) {
  getPost(id: $id) {
    comments {
      ...CommentFragment
    }
  }
}

mutation CreateComment($postId: ID!, $content: String!) {
  createComment(postId: $postId, content: $content) {
    id
    author {
      id
      firstName
      lastName
      avatar
    }
    content
    createdAt
  }
}

mutation DeleteCommentById($id: ID!) {
  deleteCommentById(id: $id) {
    id
    author {
      id
      firstName
      lastName
      avatar
    }
    content
    createdAt
  }
}

mutation LikeComment($commentId: ID!) {
  likeComment(commentId: $commentId) {
    ...CommentFragment
  }
}

query GetCommentById($id: ID!) {
  getComment(id: $id) {
    ...CommentFragment
  }
}

fragment CommentFragment on CommentModel {
  id
  author {
    id
    firstName
    lastName
    avatar
  }
  content
  createdAt
  likes {
    id
  }
}
