query GetFeed {
  getAllPosts {
    id
    author {
      id
    }
  }
}

query GetFriendFeed {
  getFriendPosts {
    id
    author {
      id
    }
  }
}

query GetPostById($id: ID!) {
  getPost(id: $id) {
    id
    likes {
      id
    }
    author {
      id
    }
  }
}

mutation ToggleLike($id: ID!) {
  toggleLike(id: $id) {
    id
    likes {
      id
    }
    author {
      id
    }
  }
}
