query GetFeed {
  getAllPosts {
    id
    author {
      id
      firstName
      lastName
      avatar
    }
    createdAt
    textContent
    mediaContent
  }
}

query GetFriendFeed {
  getFriendPosts {
    id
    author {
      id
    }
  }
}
