fragment msgFragment on Message {
  id
  author {
    id
  }
  receivers {
    id
  }
  content
}

query GetMessages {
  getMessages {
    ...msgFragment
  }
}

mutation CreateMessage($content: String!, $chatId: String!) {
  createMessage(content: $content, chatId: $chatId) {
    ...msgFragment
  }
}

subscription NewMessage {
  newMessage {
    ...msgFragment
  }
}
