query GetChats {
  getChats {
    ...ChatFragment
  }
}

mutation CreateChat($participants: [ID!]!) {
  createChat(participants: $participants) {
    ...ChatFragment
  }
}

subscription NewChat {
  newChat {
    ...ChatFragment
  }
}

fragment ChatFragment on Chat {
  id
  participants {
    id
  }
  isDialog
}

