query GetChats {
  getChats {
    ...ChatFragment
  }
}

mutation CreateChat($participants: [ID!]!) {
  createChat(participants: $participants) {
    ...ChatFragment
  }
}

mutation DeleteChatById($chatId: ID!) {
  deleteChatById(chatId: $chatId) {
    ...ChatFragment
  }
}

subscription NewChat {
  newChat {
    ...ChatFragment
  }
}

fragment ChatFragment on Chat {
  id
  participants {
    id
    firstName
    lastName
  }
  isDialog
  messages {
    id
    content
    author {
      id
      firstName
      lastName
    }
    createdAt
    chatId
    lastEdit
  }
}
