mutation EditEmail($newEmail: String!) {
  editEmail(newEmail: $newEmail) {
    ...UserFragment
  }
}

mutation EditUserName($newFirstName: String!, $newLastName: String!) {
  editUsername(newFirstName: $newFirstName, newLastName: $newLastName) {
    ...UserFragment
  }
}
