mutation EditEmail($newEmail: String!) {
  editEmail(newEmail: $newEmail) {
    ...UserFragment
  }
}

mutation EditUserName($newFirstName: String!, $newLastName: String!) {
  editUsername(newFirstName: $newFirstName, newLastName: $newLastName) {
    ...UserFragment
  }
}

mutation EditPassword($input: UpdatePasswordInput!) {
  editPassword(input: $input) {
    ...UserFragment
  }
}

mutation ToggleTheme($input: RestInput!) {
  toggleTheme(input: $input)
    @rest(type: "Theme", path: "/theme", method: "POST") {
    id
    userId
    isLight
  }
}
