fragment PostFragment on Post {
  id
  createdAt
  author {
    id
  }
}

mutation CreatePost {
  createPost {
    ...PostFragment
  }
}

subscription NewPost {
  newPost {
    ...PostFragment
  }
}

query GetPosts {
  getPosts {
    ...PostFragment
  }
}


query GetCurrentUser {
  getCurrentUser {
    firstName
    lastName
  }
}


query GetUserByID($id: ID!) {
  getUserById(id: $id) {
    firstName
    lastName
  }
}
