fragment PostFragment on Post {
  id
  createdAt
  author {
    id
  }
}

mutation CreatePost {
  createPost {
    ...PostFragment
  }
}

subscription NewPost {
  newPost {
    ...PostFragment
  }
}

query GetPosts($author: ID) {
  getPosts(author: $author) {
    ...PostFragment
  }
}

query GetUser($id: ID) {
  getUser(id: $id) {
    id
    firstName
    lastName
  }
}

query GetUserByID($id: ID!) {
  getUserById(id: $id) {
    firstName
    lastName
  }
}

query GetUsers {
  getUsers {
    id
    firstName
    lastName
    avatar
  }
}
