fragment PostFragment on Post {
  id
  author
  createdAt
}

mutation CreatePost($token: String!) {
  createPost(token: $token) {
    ...PostFragment
  }
}

subscription NewPost($token: String!) {
  newPost(token: $token) {
    ...PostFragment
  }
}
